name: PmGPT
version: 0.1
api: 4.0.0
main: GLX20\Main
author: GLX20
commands:
  chatgpt:
    permission: pmgpt.use
    description: "Ask a question to ChatGPT"
    permission-message: "ยง4Not allowed to use PmGPT"

permissions:
  pmgpt.use:
    default: op
    description: Allows use PmGPT
